name: 測試並部署

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 下載 repo
        uses: actions/checkout@v6

      - name: 檢查檔案
        run: |
          echo "檢查當前路徑: $(pwd)"
          echo "列出當前路徑的檔案:"
          ls -al

      - name: 設定 Node.js 環境
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: 安裝 npm 套件
        run: npm install

      - name: TypeScript 型別檢查
        run: npm run typecheck

      - name: ESLint 檢查
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: 下載 repo
        uses: actions/checkout@v6

      - name: 設定 Node.js 環境
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: 安裝 npm 套件
        run: npm install

      - name: 建置專案
        env:
          VITE_OPEN_WEATHER_API_URL: ${{ vars.VITE_OPEN_WEATHER_API_URL }}
          VITE_OPEN_WEATHER_API_KEY: ${{ secrets.VITE_OPEN_WEATHER_API_KEY }}
        run: npm run build

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
